version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/marcelhaindl/bkp/cmd/version.Version={{.Version}}
      - -X github.com/marcelhaindl/bkp/cmd/version.Commit={{.Commit}}
      - -X github.com/marcelhaindl/bkp/cmd/version.BuildDate={{.Date}}

release:
  prerelease: auto

universal_binaries:
  - replace: true

archives:
  - formats: [tar.gz]
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    builds_info:
      group: root
      owner: root
    files:
      - README.md

checksum:
  name_template: "checksums.txt"
