name: Feature Request
description: Got an idea for a feature that the application doesn't have currently?  Submit your idea here!
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        1. Please speak English, this is the language all maintainers can speak and write.
        2. Please take a moment to check that your feature hasn't already been suggested.
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      placeholder: |
        I think it would be great if the application had...
    validations:
      required: true
